### ISSUE TITLE
Hashsum

### ISSUE THREAD

**Issue by pzant** [dpowcore-project/dpowcoin#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

The SHA256SUM file contains hashes from previous versions.

### Expected behaviour

Hashes of new files.

### Steps to reproduce

Just check hashes.

### How did you obtain Dpowcoin Core

Pre-built binaries

### What version of Dpowcoin core are you using?

any

### Operating system and version

any

**Comment by mraksoll4** [comment]
Updated.
